name: Probe issue
on:
  issues:
    types: [opened, reopened]
jobs:
  show-issue-context:
    runs-on: ubuntu-latest

    steps:
      - name: Show context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
